### ISSUE TITLE
Performance of the GetProof function leaves a bit to be desired

### ISSUE THREAD

**Issue by mlockett42** [lontivero/MerkleTools#2]
I am creating a program the creates a Merkle Tree of approximately 8000 values. I wish to cache the proofs so we don't have to load the Merkle Tree every time. However it appears to take about 1/20th of a second to run the GetProof function against this tree. This gives several minutes to generate the full set of proofs. (I am using an i5 pc to develop on)

I believe this kind of operation should be much quicker and take at most 1 second to get 8000 proofs.

I believe the reason is that the leaves are stored as an unsorted list and instead some be stored in a Dictionary

**Comment by lontivero** [comment]
I didn't remember this project. I will take a look, it has to be something easy to improve.

**Comment by lontivero** [comment]
Ok, it is done here 8bb6a7dbc48a0a40879d46457d5f9cac58a55b7a

There is a new test called `TenThousandItems` that generates a tree containing 10,000 elements and get all the proofs in less than a second.
